# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://mayank-kr-verma.github.io/
baseurl: /
author: Mayank kumar
description: Personal website and blog


# needed for travis-ci build
exclude: [vendor]
